### ISSUE TITLE
When will be the results posted

### ISSUE THREAD

**Issue by Fronteist** [PixelsCamp/pixels_camp_2016_talks#61]
I have a question:

When do we know which talks are going to be approved? I am planning to visit Pixels camp, but I would like to know which talks are going to be there.

Thanks

**Comment by LuRsT** [comment]
@Fronteist, given this [tweet](https://twitter.com/pixelscamp/status/766639530665447424) I'd say the talks will be decided in 2-3 weeks (assuming that they take a week or two to decide on them), so I'd suggest you to [apply](https://pixels.camp/apply/) if you haven't already in order to get an invite :)
